version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    env_file: 
      - .env
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl --fail --silent http://localhost:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
    healthcheck:
      test: curl --fail --silent http://localhost:5601/api/status || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  es_data: